name: Check the ArcGis endpoint availibility

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: pip install aiohttp

      - name: isort
        run: isort --line-width 88 --trailing-comma -m 3 --check-only .
      
      - name: black
        run: black --check .
      
      - name: flake8
        run: flake8 --max-line-length 88 .
      
      - name: pydocstyle
        run: pydocstyle .
      
      - name: mypy
        run: mypy --ignore-missing-imports --follow-imports=silent custom_components/rki_covid
  bandit:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: Bandit Check (Python security linter)
        uses: jpetrucciani/bandit-check@master
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
